[build]
builder = "Dockerfile"

[deploy]
startCommand = "uvicorn app.audio:app --host 0.0.0.0 --port 8080"

[env]
PYTHONUNBUFFERED = "1"
DEBIAN_FRONTEND = "noninteractive"

[service]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 120
